# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/a8c-ci-toolkit#2.18.1
  # Common environment values to use with the `env` key.
  - &common_env
    # Be sure to also update the `.xcode-version` file when updating the Xcode image/version here
    IMAGE_ID: xcode-15.1

# This is the default pipeline – it will build and test the app
steps:
  - group: "Linters"
    steps:
      - label: ':swift: SwiftLint'
        command: .buildkite/commands/swiftlint.sh
        agents:
          queue: default
        plugins:
          - docker#v5.8.0:
              # TODO: Ensure the same version as local is used, i.e. with Buildkite env vars injection during pipeline upload
              image: ghcr.io/realm/swiftlint:latest
              mount-buildkite-agent: true # Needed for calling `buildkite-agent annotate`
        notify:
          - github_commit_status:
              context: SwiftLint
