 # 'ref' should have either a commit or tag key.
 # If both are set, tag will take precedence.
 #
 # We have automation that reads and updates this file.
 # Leaving commented keys is discouraged, because the automation would ignore them and the resulting updates would be noisy
 # If you want to use a local version, please use the LOCAL_GUTENBERG environment variable when calling CocoaPods.
 #
 # Example:
 #
 #   LOCAL_GUTENBERG=../my-gutenberg-fork bundle exec pod install
ref:
  # tag: v1.111.0-alpha2
  commit: 53849820591e9b7b0a4947fd9dd8d45f5fddda40
github_org: wordpress-mobile
repo_name: gutenberg-mobile
